id: app
title: Database
type: project
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: ~
  description:
    short: NIST SP 800-53 Rev 5 Compliance of Database
    long: Generates compliance documentation of Database per NIST SP 800-53 Rev 5
      controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: PM
introduction:
  format: markdown
  template: |-
    DESCR
    This application will make sure you are properly using Database to protect an information system per NIST SP 800-53 Rev 5 controls.
protocol:
- govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp
- govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp/database
output:
- id: ssp_nistsp80053r5_control_ac_3_impl
  title: NIST SP 800-53 Rev 5 AC-3 Control Implementation
  format: markdown
  template: |
    {{organization}} uses Database to        Enforce approved authorizations for logical access to information and system resources in

    accordance with applicable access control policies.
     DESCR
- id: ssp_nistsp80053r5_control_ac_6_9_impl
  title: NIST SP 800-53 Rev 5 AC-6(9) Control Implementation
  format: markdown
  template: |
    {{organization}} uses Database to audit the execution of privileged functions. DESCR
- id: ssp_nistsp80053r5_control_ac_7_impl
  title: NIST SP 800-53 Rev 5 AC-7 Control Implementation
  format: markdown
  template: >
    {{organization}} uses Database to a.    Enforce a limit of [Assignment: organization-defined
    number] consecutive invalid logon
          attempts by a user during a [Assignment: organization-defined time-period];
    and b.    Automatically [Selection (one or more): lock the account/node for an
    <3>; lock the account/node until released by an administrator; delay next logon
    prompt per <4>; take <5>] when the maximum number of unsuccessful
          attempts is exceeded.
     DESCR
- id: ssp_nistsp80053r5_control_au_3_impl
  title: NIST SP 800-53 Rev 5 AU-3 Control Implementation
  format: markdown
  template: |
    {{organization}} uses Database to the system generates audit records containing information that establishes what type of
    event occurred, when the event occurred, where the event occurred, the source of the event, the
    outcome of the event, and the identity of any individuals or subjects associated with the event.
     DESCR
- id: ssp_nistsp80053r5_control_au_5_impl
  title: NIST SP 800-53 Rev 5 AU-5 Control Implementation
  format: markdown
  template: |
    {{organization}} uses Database to a.    Alert [Assignment: organization-defined personnel or roles] in the event of an audit
          processing failure within [Assignment: organization-defined time-period]; and
    b.    Take the following additional actions: [Assignment: organization-defined actions to be taken].
     DESCR
- id: ssp_nistsp80053r5_control_au_12_impl
  title: NIST SP 800-53 Rev 5 AU-12 Control Implementation
  format: markdown
  template: |
    {{organization}} uses Database to a.    Provide audit record generation capability for the auditable event types in AU-2 a. at
          [Assignment: organization-defined system components];
    b.    Allow [Assignment: organization-defined personnel or roles] to select which auditable event
          types are to be audited by specific components of the system; and
    c.    Generate audit records for the event types defined in AU-2 d. with the content in AU-3.
     DESCR
- id: ssp_nistsp80053r5_control_ia_2_impl
  title: NIST SP 800-53 Rev 5 IA-2 Control Implementation
  format: markdown
  template: |
    {{organization}} uses Database to uniquely identify and authenticate organizational users or processes acting on behalf of
    organizational users.
     DESCR
- id: ssp_nistsp80053r5_control_ia_2_1_impl
  title: NIST SP 800-53 Rev 5 IA-2(1) Control Implementation
  format: markdown
  template: |
    {{organization}} uses Database to implement multifactor authentication for access to privileged accounts. DESCR
- id: ssp_nistsp80053r5_control_ia_2_8_impl
  title: NIST SP 800-53 Rev 5 IA-2(8) Control Implementation
  format: markdown
  template: |
    {{organization}} uses Database to implement replay-resistant authentication mechanisms for access to [Selection (one or more): privileged accounts; non-privileged accounts].
     DESCR
- id: ssp_nistsp80053r5_control_sc_12_impl
  title: NIST SP 800-53 Rev 5 SC-12 Control Implementation
  format: markdown
  template: |
    {{organization}} uses Database to establish and manage cryptographic keys for required cryptography employed within the
    system in accordance with [Assignment: organization-defined requirements for key generation, distribution, storage, access, and destruction].
     DESCR
- id: ssp_nistsp80053r5_control_sc_13_impl
  title: NIST SP 800-53 Rev 5 SC-13 Control Implementation
  format: markdown
  template: |
    {{organization}} uses Database to        Implement the following cryptographic uses and type of cryptography for each use:

    [Assignment: organization-defined cryptographic uses and type of cryptography required for each use].
     DESCR
