id: app
title: Monitoring Infrastructure
type: project
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: ~
  description:
    short: NIST SP 800-53 Rev 5 Compliance of Monitoring Infrastructure
    long: Generates compliance documentation of Monitoring Infrastructure per NIST
      SP 800-53 Rev 5 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: PM
introduction:
  format: markdown
  template: >-
    DESCR

    This application will make sure you are properly using Monitoring Infrastructure
    to protect an information system per NIST SP 800-53 Rev 5 controls.
protocol:
- govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp
- govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp/monitoring-infrastructure
output:
- id: ssp_nistsp80053r5_control_si_4_impl
  title: NIST SP 800-53 Rev 5 SI-4 Control Implementation
  format: markdown
  template: |
    {{organization}} uses Monitoring Infrastructure to a.   Monitor the system to detect:
         1.    Attacks and indicators of potential attacks in accordance with [Assignment:
    organization-defined monitoring objectives]; and
         2.    Unauthorized local, network, and remote connections;
    b.   Identify unauthorized use of the system through [Assignment: organization-defined techniques and methods];
    c.   Invoke internal monitoring capabilities or deploy monitoring devices:
         1.    Strategically within the system to collect organization-determined
    essential information;
               and
         2.    At ad hoc locations within the system to track specific types of transactions
    of interest to
               the organization;
    d.   Protect information obtained from intrusion-monitoring tools from unauthorized access,
         modification, and deletion;
    e.   Adjust the level of system monitoring activity when there is a change in risk to organizational
         operations and assets, individuals, other organizations, or the Nation;
    f.   Obtain legal opinion regarding system monitoring activities; and
    g.   Provide [Assignment: organization-defined system monitoring information] to [Assignment: organization-defined personnel or roles] [Selection (one or more): as needed; <5>].
     DESCR
