id: project
title: Develop System Security Plan (SSP) for FISMA
type: project
version: 1
snippet:
  format: html
  template: ""
introduction:
  format: markdown
  template: |
    ## Preparing a System Security Plan

    This project will guide you through preparing a System Security Plan (SSP) under the NIST Risk Management Framework to get an Authority to Operate the {{project}}.

    As you answer questions, you will be guided step-by-step on how to secure the {{project}} system according to {{organization}} policy. Your answers will be automatically incorporated into your SSP.

questions:
- id: system_stack
  title: About Your System Stack
  type: module
  module-id: system_stack
  tab: Basic Info
  group: About the Information System

- id: control_au_1
  title: AU-1 Audit And Accountability Policy And Procedures
  type: module
  module-id: control_au_1
  tab: Org Responsibilities
  group: Policy

- id: control_au_multi
  title: Audit and Logs Module
  type: module
  module-id: control_au_multi
  tab: System Responsibilities
  group: Audit and Logs

- id: control_sc_7
  title: SC-7 Boundary Protection
  type: module
  module-id: control_sc_7
  tab: System Responsibilities
  group: Secure Communications

- id: ssp
  title: Preview Draft SSP
  type: module
  module-id: ssp
  tab: Preview SSP
  group: Draft 

- id: howto_ssp
  title: "SSP 101: What's a System Security Plan"
  type: module
  module-id: howto_ssp
  tab: How To
  group: Tutorials

- id: howto_security_categorization
  title: FIPS 199 and Categorizing Your System Security Sensitivity
  type: module
  module-id: howto_security_categorization
  tab: How To
  group: Tutorials

- id: howto_scan
  title: Scanning Your System for STIG Compliance
  type: module
  module-id: howto_scan
  tab: How To
  group: Tutorials

- id: howto_govready_kbs
  title: Using the GovReady Knowledgebase
  type: module
  module-id: howto_govready_kbs
  tab: How To
  group: Reference

- id: howto_official_policy
  title: Finding and Using Official Policies
  type: module
  module-id: howto_official_policy
  tab: How To
  group: Reference

