id: project
title: Develop System Security Plan (SSP) for FISMA
type: project
version: 1
snippet:
  format: html
  template: ""
introduction:
  format: markdown
  template: |
    This project will help you become compliant with several NIST 800-53 control families.
questions:
- id: system_stack
  title: About Your System Stack
  type: module
  module-id: system_stack
  tab: Basic Info
  group: About the Information System

- id: control_sc_7
  title: SC-7 Boundary Protection
  type: module
  module-id: control_sc_7
  tab: Controls
  group: Secure Communications

- id: ssp
  title: Preview Draft SSP
  type: module
  module-id: ssp
  tab: Draft SSP
  group: Draft SSP
