id: project
title: Develop System Security Plan (SSP) for FISMA
type: project
version: 1

snippet:
  format: html
  template: ""

introduction:
  format: markdown
  template: |
    ## Preparing a System Security Plan

    This project will guide you through preparing a System Security Plan (SSP) under the NIST Risk Management Framework to get the {{project}} its Authority to Operate.

    As you and your team answer questions, you will be guided step-by-step on how to secure the {{project}} system according to {{organization}} policy. Your answers will be automatically incorporated into your SSP.

    At any time you can preview your SSP, share it or export the data for import into other systems.

export_button_label: Export System Description and Control Information

questions:
- id: howto_ssp
  title: "SSP 101: What's a System Security Plan"
  type: module
  module-id: howto_ssp
  tab: 1. How To
  group: Start Here

- id: system_name
  title: System name and details
  type: module
  module-id: system_name
  tab: 2. Basic Info
  group: About your information system

- id: system_stack
  title: About your system stack
  type: module
  module-id: system_stack
  tab: 2. Basic Info
  group: About your information system

- id: howto_security_stories
  title: Add security stories to your sprints
  type: module
  module-id: howto_security_stories
  tab: 2. Basic Info
  group: About your information system

- id: control_sc_7
  title: SC-7 Boundary Protection
  type: module
  module-id: control_sc_7
  tab: 3. System Design
  group: Secure Communications

- id: control_au_multi
  title: Audit and Logs Module
  type: module
  module-id: control_au_multi
  tab: 3. System Design
  group: Audit and Logs

- id: control_au_1
  title: AU-1 Audit And Accountability Policy And Procedures
  type: module
  module-id: control_au_1
  tab: 4. System Operations
  group: Policy

- id: ssp
  title: Preview draft SSP
  type: module
  module-id: ssp
  placement: action-buttons

- id: howto_security_categorization
  title: FIPS 199 and categorizing your system security sensitivity
  type: module
  module-id: howto_security_categorization
  tab: 1. How To
  group: Additional Tutorials

- id: howto_scan
  title: Scanning your system for stig compliance
  type: module
  module-id: howto_scan
  tab: 1. How To
  group: Additional Tutorials

- id: howto_govready_kbs
  title: Using the GovReady Knowledgebase
  type: module
  module-id: howto_govready_kbs
  tab: 1. How To
  group: Reference

- id: howto_official_policy
  title: Finding and using official policies
  type: module
  module-id: howto_official_policy
  tab: 1. How To
  group: Reference

- id: evidence
  title: Create an evidence bag
  type: module-set
  module-id: evidence
  tab: 2. Basic Info
  group: Supporting documents

- id: issuepack
  title: Create a Jira IssuePack
  type: module-set
  module-id: issuepack
  tab: 3. IssuePacks
  group: IssuePacks

output:
- title: Dashboard
  glyphicon: dashboard
  format: html
  template: |
      <link href="https://plugin.govready.com/app.dist.css" rel="stylesheet">

      <div class="container text-center" id="auth0-widget" style="display: none;max-width:700px;margin: 0 auto;">
          <p>To get started, create a new GovReady account (or login with your
          existing account) and we'll connect your site to our monitoring
          API.</p><!-- WIDGET -->
          <div class="widget-container" id="widget-container" style="margin: 1em auto;width:300px;"></div>
          <p>By creating and connecting to an account, you are opting in to the
          GovReady Terms of Service. GovReady
          will contact your site periodically to collect information about your
          WordPress plugins, users and server information. 
          <a href="https://github.com/GovReady/GovReady-CMS-API/wiki/Security" target="_blank">Learn more</a>.</p>
      </div>
      <div id="root" style="height: 100%"></div>
      <script src="https://cdn.auth0.com/js/lock-9.1.min.js"></script>
      <script>
        // Creates a new cookie
        function setCookie(cname, cvalue, exmins) {
          var d = new Date();
          d.setTime(d.getTime() + (exmins*60*1000));
          var expires = "expires="+ d.toUTCString();
          document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
        }

        // Gets the value of a cookie
        function getCookie(cname) {
          var name = cname + "=";
          var ca = document.cookie.split(';');
          for(var i = 0; i <ca.length; i++) {
              var c = ca[i];
              while (c.charAt(0)==' ') {
                  c = c.substring(1);
              }
              if (c.indexOf(name) == 0) {
                  return c.substring(name.length,c.length);
              }
          }
          return "";
        }

        // Deletes a cookie
        function deleteCookie(cname) {
          var cvalue = getCookie( cname );
          if( cvalue ) {
            document.cookie = cname + "=" + cvalue + ";expires=Thu, 01 Jan 1970 00:00:01 GMT;path=/";
          }
        }

        // After you login, we reload the page, so we want to set the active tab as Dashboard.
        if (getCookie('dashboardLoginRedirect')) {
          setTimeout(function(){ 
            $('#project-tabs li a[href="#document-1"]').click(); 
          }, 1000);
          
          setCookie('dashboardLoginRedirect', false, 0);
        }

        // Add the settings
        window.govready = {
          mode: 'standalone', // Embedded in GovReady Q, is only Manual Measures, etc
          //mode: 'agent' : Embeded in GovReady Q, but has a agent (WP/Drupal)
          connectUrl: 'https://plugin.govready.com/v1.0', // If this is set, then we need to talk to the GovReady API directly.
          domain: 'govready.auth0.com',
          client_id: 'HbYZO5QXKfgNshjKlhZGizskiaJH9kGH',
          access_token: getCookie('govreadyDashboardToken')
        };

        // Show the Auth0 Authenicate box if necessary
        if (!window.govready.access_token) {
          //jQuery('#auth0-widget').show();
          document.getElementById("auth0-widget").style.display = 'block';
          document.getElementById("root").style.display = 'none';

          var lock = new Auth0Lock(window.govready.client_id, window.govready.domain);

          // Show the Auth0 signin modal, and deal with the response
          lock.show({
            icon: 'https://avatars1.githubusercontent.com/u/6815262?v=3&s=200',
            container: 'widget-container',
            focusInput: false,
            popup: false,
            authParams: {
              scope: 'openid'
            },
            device: 'govready-q'
          }, function (err, profile, token) {
            if (err) {
              return;
            }

            setCookie('govreadyDashboardToken', token, 60);
            setCookie('dashboardLoginRedirect', true, 60);

            location.reload();
          });

        }
      </script>
      <script src="https://plugin.govready.com/vendor.dist.js" type="text/javascript"></script>
      <script src="https://plugin.govready.com/app.dist.js" type="text/javascript"></script>

