id: project
title: I want to complete a FedRAMP System Security Plan (SSP) for a Low/Moderate System
type: project
version: 1
introduction:
  format: markdown
  template: |
    This project will help you complete a FedRAMP System Security Plan (SSP) for a Low/Moderate system.

questions:
  - id: information_system_name_title
    title: Information System Name and Title
    type: module
    module-id: information_system_name_title
    tab: Basic Info
    group: About the Information System

  - id: responsible_roles
    title: Responsible Roles
    type: module
    module-id: responsible_roles
    tab: Basic Info
    group: About the Information System

  - id: system_stack
    title: About Your System Stack
    type: module
    module-id: system_stack
    tab: Basic Info
    group: About the Information System

  - id: information_types
    title: Information Types
    type: module-set
    module-id: information_type
    tab: Basic Info
    group: Information Types

  - id: control_au_1
    title: AU-1 Audit and Accountability Policy and Procedures
    type: module
    module-id: control_au_1
    tab: Controls
    group: Audit and Accountability (AU)

  - id: control_au_2_3
    title: AU-2 (3) Control Enhancement to AU-2 Audit Events
    type: module
    module-id: control_au_2_3
    tab: Controls
    group: Audit and Accountability (AU)

  - id: control_pe_1
    title: PE-1 Physical And Environmental Protection Policy And Procedures
    type: module
    module-id: control_pe_1
    tab: Controls
    group: Physical And Environmental Protection (PE)

output:
  - tab: Basic Info
    format: markdown
    template: |
      # Basic Info

      General information about {{project}}.
