id: project
title: Develop System Security Plan (SSP) for FISMA
type: project
version: 1

snippet:
  format: html
  template: ""

interstitial:
  format: markdown
  template: |
    ## Prepare a System Security Plan

    Been told you need an ATO (Authority to Operate)?

    No sweat! We'll help your team...

    - Describe the *{{project}}* system and assess your risk impact level
    - Secure *{{project}}* to official {{organization}} policies
    - Prepare various assessment package artifacts

    Are you ready?

introduction:
  format: markdown
  template: |
    This project will guide you through preparing a System Security Plan (SSP) under the NIST Risk Management Framework to get the {{project}} its Authority to Operate.

export_button_label: Export System Description and Control Information

questions:
- id: system_basics
  title: Document official system name and details
  type: module
  module-id: system_name_and_details
  tab: System Profile
  group: System Description

- id: coming_soon_1
  title: Prepare re-usable system descriptions
  type: module
  module-id: coming_soon
  tab: System Profile
  group: System Description

- id: coming_soon_2
  title: Identify Points of Contact
  type: module
  module-id: coming_soon
  tab: System Profile
  group: System Description

- id: issuepack
  title: Add security stories to your issue tracker
  type: module-set
  module-id: issuepack
  tab: Agile Security Stories
  group: Security User Stories

- id: control_sc_7
  title: Protect your system's boundary
  type: module
  module-id: control_sc_7
  tab: System Security Controls
  group: SC - System and Communications Protection

- id: evidence
  title: Create evidence artifact
  type: module-set
  module-id: evidence
  tab: System Security Controls
  group: Supporting documents

- id: coming_soon_3
  title: Review artifacts
  type: module
  module-id: coming_soon
  tab: Review
  group: Review

- id: ssp
  title: Preview draft SSP
  type: module
  module-id: ssp
  placement: action-buttons

output:
  - tab: System Info
    format: markdown
    template: |
      ![](add_sec_stories_gif.gif)

  - tab: User Stories
    format: markdown
    template: |
      ![](add_sec_stories_gif.gif)

      ## Let's add security stories to your backlog