id: app
title: Drupal Website
type: project
version: 0.3.0
icon: app.png

catalog:
  vendor: GovReady PBC
  vendor_url: http://www.govready.com
  status: Operational
  version: 0.3.0
  source_url: https://github.com/GovReady/govready-q-ssp-module/tree/master/modules/drupal_website
  description:
    short: |
      Operate a Drupal website so you can get an Interim Authority to Operate.
    long: |
      This app will help you operate a Drupal website so you can get an Interim Authority to Operate.
  recommended_for:
    - key_short: Org
      value: Large
    - key_short: Tech
      value: Sophisticated
    - key_short: Role
      value: PM

questions:
  - id: web_server
    title: Web Server
    type: module
    protocol: web_server

  - id: fed_poc_cio
    title: CIO (PoC)
    type: module
    protocol: fed_poc

  - id: fed_poc_isso
    title: ISSO (PoC)
    type: module
    protocol: fed_poc_isso

  - id: fed_poc_issm
    title: ISSM (PoC)
    type: module
    protocol: fed_poc

  - id: fed_poc_developer
    title: Developer (PoC)
    type: module
    protocol: fed_poc

  - id: fed_poc_ciso
    title: CISO (PoC)
    type: module
    protocol: fed_poc

  - id: fed_poc_ao
    title: AO (PoC)
    type: module
    protocol: fed_poc

  - id: sm_policy_privacy
    title: Privacy Policy
    type: module
    protocol: sm_policy_privacy

  - id: fed_poc_pm
    title: PM (PoC)
    type: module
    protocol: fed_poc

  - id: ssp
    title: View SSP
    type: module
    module-id: ssp
    icon: checkmark.png
