id: app
title: Drupal Website
type: project
version: 0.4.0
icon: app.png

catalog:
  categories:
    - Technology
    - Great starter apps
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: Operational
  version: 0.3.0
  source_url: https://github.com/GovReady/govready-q-ssp-module/tree/master/modules/drupal_website
  description:
    short: |
      Operate a Drupal website so you can get an Interim Authority to Operate.
    long: |
      This app will help you operate a Drupal website so you can get an Interim Authority to Operate.
  recommended_for:
    - key_short: Org
      value: Large
    - key_short: Tech
      value: Sophisticated
    - key_short: Role
      value: PM

questions:
  - id: fisma_system_categorization
    title: System Categorization
    type: module
    protocol: fisma_system_categorization

  - id: web_server
    title: Web Server
    type: module
    protocol: web_server

  - id: infrastructure
    title: Infrastructure
    type: module
    protocol: opencontrol

  - id: sm_policy_privacy
    title: Privacy Policy
    type: module
    protocol: sm_policy_privacy

  - id: fed_poc_pm
    title: PM
    type: module
    protocol: fed_poc_pm
    icon: person-3.png

  - id: fed_poc_developer
    title: Developer
    type: module
    protocol: fed_poc_developer
    icon: person-3.png

  - id: fed_poc_issm
    title: ISSM
    type: module
    protocol: fed_poc_issm
    icon: person-3.png

  - id: fed_poc_isso
    title: ISSO
    type: module
    protocol: fed_poc_isso
    icon: person-3.png

  - id: fed_poc_ciso
    title: CISO
    type: module
    protocol: fed_poc_ciso
    icon: person-3.png

  - id: fed_poc_ao
    title: AO
    type: module
    protocol: fed_poc_ao
    icon: person-3.png

  - id: ssp
    title: View SSP
    type: module
    module-id: ssp
    icon: checkmark.png

