id: app
title: Log Storage
type: project
version: 0.5
icon: app.png
catalog:
  category: Technology Components
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: ~
  description:
    short: NIST SP 800-53 Rev 5 Compliance of Log Storage
    long: Generates compliance documentation of Log Storage per NIST SP 800-53 Rev
      5 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: PM
introduction:
  format: markdown
  template: |-
    DESCR
    This application will make sure you are properly using Log Storage to protect an information system per NIST SP 800-53 Rev 5 controls.
protocol:
- govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp
- govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp/log-storage
output:
- id: ssp_nistsp80053r5_control_ac_6_9_impl
  title: NIST SP 800-53 Rev 5 AC-6(9) Control Implementation
  format: markdown
  template: |
    {{organization}} uses Log Storage to audit the execution of privileged functions. DESCR
- id: ssp_nistsp80053r5_control_au_4_impl
  title: NIST SP 800-53 Rev 5 AU-4 Control Implementation
  format: markdown
  template: |
    {{organization}} uses Log Storage to allocate audit record storage capacity to accommodate [Assignment: organization-defined audit record retention requirements].
     DESCR
- id: ssp_nistsp80053r5_control_au_5_impl
  title: NIST SP 800-53 Rev 5 AU-5 Control Implementation
  format: markdown
  template: |
    {{organization}} uses Log Storage to a.    Alert [Assignment: organization-defined personnel or roles] in the event of an audit
          processing failure within [Assignment: organization-defined time-period]; and
    b.    Take the following additional actions: [Assignment: organization-defined actions to be taken].
     DESCR
- id: ssp_nistsp80053r5_control_au_8_impl
  title: NIST SP 800-53 Rev 5 AU-8 Control Implementation
  format: markdown
  template: |
    {{organization}} uses Log Storage to a.    Use internal system clocks to generate time stamps for audit records; and
    b.    Record time stamps for audit records that can be mapped to Coordinated Universal Time or
          Greenwich Mean Time and meets [Assignment: organization-defined granularity of time measurement].
     DESCR
- id: ssp_nistsp80053r5_control_au_9_impl
  title: NIST SP 800-53 Rev 5 AU-9 Control Implementation
  format: markdown
  template: |
    {{organization}} uses Log Storage to protect audit information and audit tools from unauthorized access, modification, and
    deletion.
     DESCR
- id: ssp_nistsp80053r5_control_ia_2_impl
  title: NIST SP 800-53 Rev 5 IA-2 Control Implementation
  format: markdown
  template: |
    {{organization}} uses Log Storage to uniquely identify and authenticate organizational users or processes acting on behalf of
    organizational users.
     DESCR
- id: ssp_nistsp80053r5_control_ia_2_1_impl
  title: NIST SP 800-53 Rev 5 IA-2(1) Control Implementation
  format: markdown
  template: |
    {{organization}} uses Log Storage to implement multifactor authentication for access to privileged accounts. DESCR
- id: ssp_nistsp80053r5_control_ia_2_8_impl
  title: NIST SP 800-53 Rev 5 IA-2(8) Control Implementation
  format: markdown
  template: |
    {{organization}} uses Log Storage to implement replay-resistant authentication mechanisms for access to [Selection (one or more): privileged accounts; non-privileged accounts].
     DESCR
