id: project
title: Sample Data Calls
type: project
version: 1

introduction:
  format: markdown
  template: |
    This project provides sample data calls.

questions:
- id: sample_data_call_1
  title: "Sample Data Call 1"
  type: module-set
  module-id: sample_data_call_1
  tab: Samples
  group: Samples
