id: app
title: Django App Deployed with Docker
type: project
version: 0.5
icon: app.png
protocol:
  - govready.com/apps/compliance/2018/it-system
catalog:
  category: IT System Templates
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: https://github.com/GovReady/govready-apps-dev/django-docker-system
  description:
    short: |
      Compliance under NIST RMF for a Django application deployed using Docker.
    long: |
      This compliance app will help you achieve compliance for a Django application deployed
      using Docker. The app will produce compliance documents and artifacts for NIST SP 800-53 Rev 5
      and NIST SP 800-171 Rev 1.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: PM
introduction:
  format: markdown
  template: |
      This compliance app will help you achieve compliance for a Django application deployed
      using Docker. The app will produce compliance documents and artifacts for NIST SP 800-53 Rev 5
      and NIST SP 800-171 Rev 1.
questions:
- id: system_profile
  title: Sytem Profile
  type: module
  protocol: govready.com/apps/compliance/2018/basic-system-description
  group: System Overview
- id: system_categorization
  title: Sytem Categorization
  type: module
  protocol: govready.com/apps/compliance/2018/fisma/system-categorization
  group: Sytem Categorization
