id: app
title: Router at External Boundary
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-171-r1-ssp
- govready.com/apps/compliance/2017/router
version: 0.5
icon: app.png
catalog:
  category: Technology Components
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: draft
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST SP 800-171) Compliance of a Router at an External Boundary
    long: Generates compliance documentation of a generic router at an external
      network boundary as it pertains to managing
      the security of CUI (Controlled Unclassified Information) as per NIST SP 800-171
      controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    A router is a device for connecting networks. This compliance app is for routers
    at an external network boundary, i.e. routers that connect IT systems to the Internet.

    This application will make sure you are properly using a router to protect
    CUI (Controlled Unclassified Information) as per NIST SP 800-171 controls.
questions:
- id: questions
  title: Questions
  type: module
  module-id: questions
output:
- id: ssp_nist800171r1_3_1_1
  title: NIST SP 800-171 3.1.1 Control Implementation
  format: markdown
  template: |
    {{organization}} uses a ({{questions.product_name}}) to limit access to the
    network and connected devices.
    {% if "allopen" not in questions.inbound_ports_open %}Inbound network communications traffic is denied by default.{% endif %}
    {% if questions.external_access_control %}{{questions.external_access_control}}{% endif %}
    {% if questions.internal_access_control %}{{questions.internal_access_control}}{% endif %}

- id: ssp_nist800171r1_3_1_2
  title: NIST SP 800-171 3.1.2 Control Implementation
  format: markdown
  template: >+
    {{organization}}'s router ({{questions.product_name}}) filters communications
    to limit system access to the types of transactions and functions that authorized users
    are permitted to execute.
    {% if "allopen" not in questions.outbound_ports_open %}
    Outbound network communications traffic is denied by default and network communications
    traffic for authorized functions are permitted by exception (i.e., deny all, permit by
    exception). Ports {{questions.outbound_ports_open.text}} are open for outbound connections.
    {% if questions.outbound_ports_open_other %}{{questions.outbound_ports_open_other}}{% endif %}
    {% endif %}
    {% if questions.outbound_filtering %}{{questions.outbound_filtering}}{% endif %}
    {% if "allopen" not in questions.inbound_ports_open %}
    Inbound network communications traffic is denied by default and network communications
    traffic for authorized functions are permitted by exception (i.e., deny all, permit by
    exception). Ports {{questions.outbound_ports_open.text}} are open for inbound connections.
    {% if questions.inbound_ports_open_other %}{{questions.inbound_ports_open_other}}{% endif %}
    {% endif %}
    {% if questions.inbound_filtering %}{{questions.inbound_filtering}}{% endif %}

- id: ssp_nist800171r1_3_1_7
  title: NIST SP 800-171 3.1.7 Control Implementation
  format: markdown
  template: >+
    {{organization}}'s router ({{questions.product_name}}) has been configured to prevent
    non-privileged users from executing administrative functions on the router by disabling the
    default administrative account and adding administrative accounts only for privileged users.
    The router logs administrative functions and the logs are audited periodically.

- id: ssp_nist800171r1_3_1_8
  title: NIST SP 800-171 3.1.8 Control Implementation
  format: markdown
  template: |+
    {{organization}}'s router ({{questions.product_name}}) limits unsuccessful attempts
    to log in to its administrative control panel.

- id: ssp_nist800171r1_3_1_11
  title: NIST SP 800-171 3.1.11 Control Implementation
  format: markdown
  template: |+
    {{organization}}'s router ({{questions.product_name}}) terminates administrative
    user sessions for its administrative control panel after a period of inactivity.

- id: ssp_nist800171r1_3_1_12
  title: NIST SP 800-171 3.1.12 Control Implementation
  format: markdown
  template: |+
    Remote access sessions are established through Virtual Private Network (VPN) connections
    managed by {{organization}}'s router ({{questions.product_name}}). The router monitors
    and controls remote access sessions.

- id: ssp_nist800171r1_3_1_13
  title: NIST SP 800-171 3.1.13 Control Implementation
  format: markdown
  template: |+
    Remote access sessions are established through Virtual Private Network (VPN) connections
    managed by {{organization}}'s router ({{questions.product_name}}). The router enforces
    encryption on the external network for VPN connections.

- id: ssp_nist800171r1_3_1_14
  title: NIST SP 800-171 3.1.14 Control Implementation
  format: markdown
  template: |+
    Remote access sessions to systems on the internal network are established through Virtual
    Private Network (VPN) connections managed by {{organization}}'s router
    ({{questions.product_name}}).

- id: ssp_nist800171r1_3_1_15
  title: NIST SP 800-171 3.1.15 Control Implementation
  format: markdown
  template: |+
    Remote access sessions to systems on the internal network are established through Virtual
    Private Network (VPN) connections managed by {{organization}}'s router
    ({{questions.product_name}}). The router only allows remote access connections from
    authorized users.

- id: ssp_nist800171r1_3_1_16
  title: NIST SP 800-171 3.1.16 Control Implementation
  format: markdown
  template: |+
    {% if questions.wifi_authorization %}
    {{organization}}'s router ({{questions.product_name}}) is a wifi access point.
    {{questions.wifi_authorization}}
    {% endif %}

- id: ssp_nist800171r1_3_1_17
  title: NIST SP 800-171 3.1.17 Control Implementation
  format: markdown
  template: |+
    {% if questions.wifi_authorization %}
    {{organization}}'s router ({{questions.product_name}}) is a wifi access point.
    The router accepts only encrypted wifi connections.
    {% endif %}

- id: ssp_nist800171r1_3_1_18
  title: NIST SP 800-171 3.1.18 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses a ({{questions.product_name}}) to control connection of mobile devices.

- id: ssp_nist800171r1_3_1_20
  title: NIST SP 800-171 3.1.20 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses a ({{questions.product_name}}) to limit access to the
    network and connected devices.
    {% if "allopen" not in questions.inbound_ports_open %}Inbound network communications traffic is denied by default.{% endif %}
    {% if questions.external_access_control %}{{questions.external_access_control}}{% endif %}
    {% if questions.internal_access_control %}{{questions.internal_access_control}}{% endif %}

- id: ssp_nist800171r1_3_1_2
  title: NIST SP 800-171 3.1.2 Control Implementation
  format: markdown
  template: >+
    {% if "allopen" not in questions.outbound_ports_open %}
    {{organization}}'s router ({{questions.product_name}}) denies outbound communications
    by default and permits outbound communications by exception (i.e., deny all, permit by
    exception). Ports {{questions.outbound_ports_open.text}} are open for outbound connections.
    {% if questions.outbound_ports_open_other %}{{questions.outbound_ports_open_other}}{% endif %}
    {% endif %}
    {% if questions.outbound_filtering %}
    {{organization}}'s router ({{questions.product_name}} filters communications
    to limit access to external systems.
    {{questions.outbound_filtering}}
    {% endif %}

- id: ssp_nist800171r1_3_3_1
  title: NIST SP 800-171 3.3.1 Control Implementation
  format: markdown
  template: >+
    {{organization}}'s router ({{questions.product_name}}) creates, protect, and retains
    system audit records to enable the monitoring, analysis, investigation,
    and reporting of unlawful, unauthorized, or inappropriate system activity.

- id: ssp_nist800171r1_3_3_4
  title: NIST SP 800-171 3.3.4 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses a ({{questions.product_name}}) to alert in the event of an audit process failure.

- id: ssp_nist800171r1_3_3_6
  title: NIST SP 800-171 3.3.6 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses a ({{questions.product_name}}) to provide audit reduction and report generation to support on-demand analysis and reporting.

- id: ssp_nist800171r1_3_3_7
  title: NIST SP 800-171 3.3.7 Control Implementation
  format: markdown
  template: >+
    The {{questions.product_name}} has a system capability that compares
    and synchronizes internal system clocks with an authoritative source to generate
    time stamps for audit records.

- id: ssp_nist800171r1_3_3_8
  title: NIST SP 800-171 3.3.8 Control Implementation
  format: markdown
  template: |+
    {{organization}}'s router ({{questions.product_name}}) protect audit information
    and audit tools from unauthorized access, modification, and deletion.

- id: ssp_nist800171r1_3_3_9
  title: NIST SP 800-171 3.3.9 Control Implementation
  format: markdown
  template: |+
    {{organization}}'s router ({{questions.product_name}}) is configured to limit management
    of its audit functionality to a subset of privileged users.

- id: ssp_nist800171r1_3_13_1
  title: NIST SP 800-171 3.13.1 Control Implementation
  format: markdown
  template: >+
    {{organization}}'s router ({{questions.product_name}}) is the primary external
    boundary for the organization. The router monitors, controls, and protects communications
    across the boundary.
    {% if "allopen" not in questions.outbound_ports_open %}
    Outbound network communications traffic is denied by default and network communications
    traffic for authorized functions are permitted by exception (i.e., deny all, permit by
    exception). Ports {{questions.outbound_ports_open.text}} are open for outbound connections.
    {% if questions.outbound_ports_open_other %}{{questions.outbound_ports_open_other}}{% endif %}
    {% endif %}
    {% if questions.outbound_filtering %}{{questions.outbound_filtering}}{% endif %}
    {% if "allopen" not in questions.inbound_ports_open %}
    Inbound network communications traffic is denied by default and network communications
    traffic for authorized functions are permitted by exception (i.e., deny all, permit by
    exception). Ports {{questions.outbound_ports_open.text}} are open for inbound connections.
    {% if questions.inbound_ports_open_other %}{{questions.inbound_ports_open_other}}{% endif %}
    {% endif %}
    {% if questions.inbound_filtering %}{{questions.inbound_filtering}}{% endif %}

- id: ssp_nist800171r1_3_13_5
  title: NIST SP 800-171 3.13.5 Control Implementation
  format: markdown
  template: >+
    {% if questions.publicly_accessible_subnetworks %}
    {{organization}} uses a ({{questions.product_name}}) to implement subnetworks for publicly accessible
    system components that are physically or logically separated from internal networks.
    {% endif %}

- id: ssp_nist800171r1_3_13_6
  title: NIST SP 800-171 3.13.6 Control Implementation
  format: markdown
  template: >+
    {% if "allopen" not in questions.outbound_ports_open %}
    {{organization}}'s router ({{questions.product_name}}) denies outbound connections by default
    and authorized network communications traffic is permitted by exception (i.e., deny all, permit by
    exception). Ports {{questions.outbound_ports_open.text}} are open for outbound connections.
    {% if questions.outbound_ports_open_other %}{{questions.outbound_ports_open_other}}{% endif %}
    {% endif %}
    {% if "allopen" not in questions.inbound_ports_open %}
    {{organization}}'s router ({{questions.product_name}}) denies inbound connections by default
    and authorized network communications traffic is permitted by exception (i.e., deny all, permit by
    exception). Ports {{questions.outbound_ports_open.text}} are open for inbound connections.
    {% if questions.inbound_ports_open_other %}{{questions.inbound_ports_open_other}}{% endif %}
    {% endif %}

- id: ssp_nist800171r1_3_13_8
  title: NIST SP 800-171 3.13.8 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses a ({{questions.product_name}}) to implement cryptographic mechanisms to prevent
    unauthorized disclosure of CUI during transmission unless otherwise protected
    by alternative physical safeguards.

- id: ssp_nist800171r1_3_13_9
  title: NIST SP 800-171 3.13.9 Control Implementation
  format: markdown
  template: >+
    Remote access sessions to systems on the internal network are established through Virtual
    Private Network (VPN) connections managed by {{organization}}'s router
    ({{questions.product_name}}). The router terminates VPN sessions after a period
    of inactivity.

- id: ssp_nist800171r1_3_13_11
  title: NIST SP 800-171 3.13.11 Control Implementation
  format: markdown
  template: |+
    {{organization}}'s router ({{questions.product_name}}) employ FIPS-validated
    cryptography for external connections on Virtual Private Networks.

- id: ssp_nist800171r1_3_13_14
  title: NIST SP 800-171 3.13.14 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses a ({{questions.product_name}}) to control and monitor the use of Voice over Internet Protocol (VoIP) technologies.

- id: ssp_nist800171r1_3_13_15
  title: NIST SP 800-171 3.13.15 Control Implementation
  format: markdown
  template: |+
    Remote access sessions to systems on the internal network are established through Virtual
    Private Network (VPN) connections managed by {{organization}}'s router
    ({{questions.product_name}}). The router uses cryptographic mechanisms to protect the
    authenticity of these communications sessions.

- id: ssp_nist800171r1_3_14_6
  title: NIST SP 800-171 3.14.6 Control Implementation
  format: markdown
  template: >+
    {{organization}} uses a ({{questions.product_name}}) to monitor organizational systems including
    inbound and outbound communications traffic, to detect attacks and indicators
    of potential attacks.