id: app
title: GovReady-Q Database
type: project
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: ~
  description:
    short: NIST SP 800-53 Rev 5 Compliance of GovReady-Q's Database
    long: Generates compliance documentation for GovReady-Q's Database per NIST SP 800-53 Rev 5
      controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: PM
introduction:
  format: markdown
  template: |-
    This application will make sure you have properly deployed the GovReady-Q Database per NIST SP 800-53 Rev 5 controls.
protocol:
- govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp
- govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp/govready.com/govready-q-database
output:
- id: ssp_nistsp80053r5_control_ac_3_impl
  title: NIST SP 800-53 Rev 5 AC-3 Control Implementation
  format: markdown
  template: |
    The GovReady-Q Database stores GovReady-Q's compliance apps and user-entered content
    such as system information and generated system security plans. All access to the
    database is through the GovReady-Q application server. The database is configured to
    allow connections only from the IP address of the GovReady-Q application server and
    only with credentials stored on the GovReady-Q application server.
- id: ssp_nistsp80053r5_control_ac_6_9_impl
  title: NIST SP 800-53 Rev 5 AC-6(9) Control Implementation
  format: markdown
  template: |
    The GovReady-Q Database logs all privileged function executions to the logging server.
    Privileged functions include database user management and database table management.
- id: ssp_nistsp80053r5_control_au_3_impl
  title: NIST SP 800-53 Rev 5 AU-3 Control Implementation
  format: markdown
  template: |
    The GovReady-Q Database logs various events to the logging server. Those events include
    what type of event occurred, when the event occurred, where the event occurred (on the
    database server), the source of the event (the GovReady-Q application server), and the
    outcome of the event. No individuals or subjects are associated with these events.
- id: ssp_nistsp80053r5_control_au_5_impl
  title: NIST SP 800-53 Rev 5 AU-5 Control Implementation
  format: markdown
  template: |
    The GovReady-Q Database alerts the {{organization}} CISO in the event of an audit
    processing failure, such as a failure to send logging information to the logging
    server, within 1 hour.
- id: ssp_nistsp80053r5_control_ia_2_impl
  title: NIST SP 800-53 Rev 5 IA-2 Control Implementation
  format: markdown
  template: |
    The GovReady-Q Database stores organizational user credentials. Each organizational
    user has a unique username in the database.
- id: ssp_nistsp80053r5_control_sc_12_impl
  title: NIST SP 800-53 Rev 5 SC-12 Control Implementation
  format: markdown
  template: |
    The GovReady-Q Application Server connects to the GovReady-Q Database over
    a connection secured by Transport Layer Security. The GovReady-Q Database
    uses a certificate generated by an {{organization}}'s certificate authority (CA),
    and the GovReady-Q Application Server is configured to ensure the database
    connection is made to a server issued one of {{organization}}'s certificates.
- id: ssp_nistsp80053r5_control_sc_13_impl
  title: NIST SP 800-53 Rev 5 SC-13 Control Implementation
  format: markdown
  template: |
    The GovReady-Q Application Server connects to the GovReady-Q Database over
    a connection secured by Transport Layer Security. The GovReady-Q Database
    uses a certificate generated by {{organization}}'s certificate authority (CA)
    which is a 2048 bit RSA key, and the client and server are configured to use
    current TLS protocols and ciphers.
