id: app
title: QNAP NAS
type: project
protocol:
- govready.com/apps/compliance/2017/nist-sp-800-171-r1-ssp
- govready.com/apps/compliance/2017/qnap-nas
version: 0.5
icon: app.png
catalog:
  category: Technology Components
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: draft
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/QNAP
  description:
    short: CUI (NIST SP 800-171) Compliance of a QNAP NAS
    long: |
      Generates compliance documentation of a QNAP NAS as it pertains to
      managing the security of CUI (Controlled Unclassified Information) as per NIST
      SP 800-171 controls.

      This app provides the following controls: NIST SP 800-171 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.7, 3.1.11, 3.1.12, 3.13.1, 3.13.2, 3.13.4, 3.13.6, 3.13.8, 3.13.9, 3.13.11, 3.13.16, 3.3.1, 3.3.2, 3.3.4, 3.3.7, 3.3.8, 3.3.9, 3.8.2, 3.8.7, 3.8.8, and 3.8.9.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: |
    QNAP is network attached storage (NAS) device for storing digital files on a network.

    Many organizations use QNAP NAS devices for storing backup copy of files, some of which may contain CUI (Controled Unclassified Information).

    This application will make sure you are properly using a QNAP NAS to protect
    CUI (Controlled Unclassified Information) as per NIST SP 800-171 controls.

questions:
- id: questions
  title: Questions
  type: module
  module-id: questions

- id: types_of_transactions_with_cui_stored_permitted_qnap
  title: types_of_transactions_with_cui_stored_permitted_qnap
  type: longtext
  impute:
    - value: "[types of transactions with cui stored permitted qnap"

- id: qnap_audit_failure_alert_individuals
  title: qnap_audit_failure_alert_individuals
  type: longtext
  impute:
    - value: "[qnap audit failure alert individuals"

output:
- id: ssp_nist800171r1_3_1_1
  title: NIST SP 800-171 3.1.1
  format: markdown
  template: >+
    {{organization}} uses QNAP {{questions.product_name}}, an on-premises file server, for network storage to store
    and protect computer files{% if questions.cui_stored %} containing CUI{% endif %}, primarily as a
    backup device for other systems (storing {{questions.what_is_stored}}).
    The QNAP file server manages file permissions to limit access to files to designated
    roles and individuals. Files containing CUI are located in shared directories on the
    QNAP device with access permisisons maintained by the QNAP file server. 
    The QNAP administration controls additionally control access to the backup files. 

- id: ssp_nist800171r1_3_1_2
  title: NIST SP 800-171 3.1.2
  format: markdown
  template: >+
    {{organization}} uses QNAP {{questions.product_name}}, a file and backup server, for network storage to store
    and protect computer files{% if questions.cui_stored %} containing CUI{% endif %}, primarily as a backup device for other systems
    ({{questions.what_is_stored}}).
    The QNAP {{questions.product_name}} limits access to the types of transactions and functions that
    authorized users are permitted to execute. The QNAP file server manages file permissions to
    control access to files to designated roles and individuals.
    The QNAP administration controls control access to the backup files. Files containing
    CUI are located in shared directories on the QNAP device with access permisisons
    maintained by the QNAP file server.
    {{types_of_transactions_with_cui_stored_permitted_qnap}}

- id: ssp_nist800171r1_3_1_3
  title: NIST SP 800-171 3.1.3
  format: markdown
  template: >+
    {{organization}} uses QNAP {{questions.product_name}}, a file and backup server, for network storage to store
    and protect computer files{% if questions.cui_stored %} containing CUI{% endif %}, primarily as a backup device for other systems
    ({{questions.what_is_stored}}).
    The QNAP device controls the flow of CUI in accordance with approved authorizations.
    The QNAP file server manages file permissions to control access to files to designated
    roles and individuals. The QNAP administration controls control access to the backup files. Files containing
    CUI are located in shared directories on the QNAP device with access permisisons
    maintained by the QNAP file server.

- id: ssp_nist800171r1_3_1_4
  title: NIST SP 800-171 3.1.4
  format: markdown
  template: |+
    {{organization}} uses QNAP {{questions.product_name}} (NAS) to separate the duties of individuals to reduce the risk of malevolent activity without collusion.

- id: ssp_nist800171r1_3_1_7
  title: NIST SP 800-171 3.1.7
  format: markdown
  template: >+
    {{organization}} uses QNAP {{questions.product_name}} (NAS) to prevent non-privileged users from executing privileged functions and audit the execution of such functions.

- id: ssp_nist800171r1_3_1_11
  title: NIST SP 800-171 3.1.11
  format: markdown
  template: |+
    {{organization}} uses QNAP {{questions.product_name}} (NAS) to terminate (automatically) a user session after a defined condition.
    __Does QNAP {{questions.product_name}} contribute to automatically terminating a user session after a defined condition?__

- id: ssp_nist800171r1_3_1_12
  title: NIST SP 800-171 3.1.12
  format: markdown
  template: |+
    {{organization}} uses QNAP {{questions.product_name}} (NAS) to monitor and control remote access sessions
    __Does QNAP {{questions.product_name}} contribute to monitoring and controling remote access sessions.?__

- id: ssp_nist800171r1_3_3_1
  title: NIST SP 800-171 3.3.1
  format: markdown
  template: >+
    {{organization}} uses QNAP {{questions.product_name}} (NAS) to create, protect, and retain system audit records to the extent needed to enable the monitoring, analysis, investigation, and reporting of unlawful, unauthorized, or inappropriate system activity.

- id: ssp_nist800171r1_3_3_2
  title: NIST SP 800-171 3.3.2
  format: markdown
  template: >+
    {{organization}} uses QNAP {{questions.product_name}} (NAS) to ensure that the actions of individual system users can be uniquely traced to those users so they can be held accountable for their actions.

- id: ssp_nist800171r1_3_3_4
  title: NIST SP 800-171 3.3.4
  format: markdown
  template: |+
    {{organization}} uses QNAP {{questions.product_name}} (NAS)'s notification feature to alert {qnap_audit_failure_alert_individuals} in the event of an audit process failure.

- id: ssp_nist800171r1_3_3_7
  title: NIST SP 800-171 3.3.7
  format: markdown
  template: >+
    The QNAP {{questions.product_name}} provide a system capability that compares and synchronizes
    internal system clocks with an authoritative source to generate time stamps for
    audit records.

- id: ssp_nist800171r1_3_3_8
  title: NIST SP 800-171 3.3.8
  format: markdown
  template: >+
    {{organization}} uses QNAP {{questions.product_name}} (NAS) to protect audit information and audit tools from unauthorized access, modification, and deletion.
    QNAP {{questions.product_name}} has a variety of features to protect files including: user authority
    management, Windows ACL, advanced folder permissions, FIPS-140-2 validated AES
    256-bit Volume-based data encryption, built-in SSL, and antivirus.

- id: ssp_nist800171r1_3_3_9
  title: NIST SP 800-171 3.3.9
  format: markdown
  template: |+
    {{organization}} uses QNAP {{questions.product_name}} (NAS) to limit management of audit functionality to a subset of privileged users
    using the various file protection features of the QNAP {{questions.product_name}}.

- id: ssp_nist800171r1_3_8_2
  title: NIST SP 800-171 3.8.2
  format: markdown
  template: >+
    {{organization}} uses QNAP {{questions.product_name}} for network storage to store and protect
    computer files containing CUI. The QNAP file server is located in a secured room
    that limits access to its media.

- id: ssp_nist800171r1_3_8_7
  title: NIST SP 800-171 3.8.7
  format: markdown
  template: |+
    {{organization}} uses QNAP {{questions.product_name}} (NAS) to control the use of removable media on system components.
    __Does the QNAP have USB slots? How is use of the USB removable media controlled?__

- id: ssp_nist800171r1_3_8_8
  title: NIST SP 800-171 3.8.8
  format: markdown
  template: |+
      __Does the QNAP have USB slots? How is use of the USB removable media controlled?__
      __What does this mean?__

- id: ssp_nist800171r1_3_8_9
  title: NIST SP 800-171 3.8.9
  format: markdown
  template: |+
    {{organization}} uses QNAP {{questions.product_name}} as an on-premises file backup device
    to store CUI. The QNAP administration controls control access to the backup files
    to protect the confidentiality of backup CUI at storage locations.
    QNAP {{questions.product_name}} has a variety of features to protect files including: user authority management, Windows ACL, advanced folder permissions, FIPS-140-2 validated AES 256-bit Volume-based data encryption, built-in SSL, and antivirus.

- id: ssp_nist800171r1_3_13_1
  title: NIST SP 800-171 3.13.1
  format: markdown
  template: >+
    {{organization}} uses QNAP {{questions.product_name}} (NAS) to monitor, control, and protect communications (i.e., information transmitted or received by organizational systems) at the external boundaries and key internal boundaries of organizational systems.
    {{organization}} uses QNAP {{questions.product_name}} for network storage to store and protect
    computer files containing CUI. The QNAP device is used as a file server. The QNAP
    file server manages file permissions to control access to files to designated
    roles and individuals. The QNAP device used as an on-premises file backup device.
    The QNAP administration controls control access to the backup files. Files containing
    CUI are located in shared directories on the QNAP device with access permisisons
    maintained by the QNAP file server.

- id: ssp_nist800171r1_3_13_2
  title: NIST SP 800-171 3.13.2
  format: markdown
  template: >+
    {{organization}} uses QNAP {{questions.product_name}} for network storage to store and protect
    computer files containing CUI. The QNAP device is used as a file server and file backup device.
    {{organization}} uses QNAP {{questions.product_name}} to support an architectural design that
    segregates files containing CUI from other systems and creates a control point
    to control and monitor access to CUI.

- id: ssp_nist800171r1_3_13_4
  title: NIST SP 800-171 3.13.4
  format: markdown
  template: >+
    {{organization}} uses QNAP {{questions.product_name}} (NAS) to prevent unauthorized and unintended information transfer via shared system resources.

- id: ssp_nist800171r1_3_13_6
  title: NIST SP 800-171 3.13.6
  format: markdown
  template: |+
    {{organization}}'s QNAP {{questions.product_name}} (NAS) denies network communications traffic by default and allow network communications traffic by exception (i.e., deny all, permit by exception).

- id: ssp_nist800171r1_3_13_8
  title: NIST SP 800-171 3.13.8
  format: markdown
  template: |+
    QNAP {{questions.product_name}}, a file server, employs built-in SSL to implement cryptographic mechanisms
    to prevent unauthorized disclosure of CUI during transmission to and from the
    QNAP device.

- id: ssp_nist800171r1_3_13_9
  title: NIST SP 800-171 3.13.9
  format: markdown
  template: |+
    {{organization}}'s QNAP {{questions.product_name}} (NAS) terminates network connections
    associated with communications sessions at the end of the sessions or after a period of
    inactivity as follows: {{questions.session_termination_settings_description}}.

- id: ssp_nist800171r1_3_13_11
  title: NIST SP 800-171 3.13.11
  format: markdown
  template: >+
    QNAP {{questions.product_name}} employs FIPS-140-2 validated AES 256-bit Volume-based data encryption
    to protect the confidentiality of the CUI stored on the device.

- id: ssp_nist800171r1_3_13_16
  title: NIST SP 800-171 3.13.16
  format: markdown
  template: >
    {{organization}} uses QNAP {{questions.product_name}} for network storage to store and protect
    computer files containing CUI at rest. The QNAP device is used as a file server
    and backup server.
    The QNAP administration controls control access to the backup files. Files containing
    CUI are located in shared directories on the QNAP device with access permisisons
    maintained by the QNAP file server.
