id: app
title: Network Infrastructure
type: project
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: ~
  description:
    short: NIST SP 800-53 Rev 5 Compliance of Network Infrastructure
    long: Generates compliance documentation of Network Infrastructure per NIST SP
      800-53 Rev 5 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: PM
introduction:
  format: markdown
  template: >-
    DESCR

    This application will make sure you are properly using Network Infrastructure
    to protect an information system per NIST SP 800-53 Rev 5 controls.
protocol:
- govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp
- govready.com/apps/compliance/2018/nist-sp-800-53-r5-ssp/network-infrastructure
output:
- id: ssp_nistsp80053r5_control_sc_7_impl
  title: NIST SP 800-53 Rev 5 SC-7 Control Implementation
  format: markdown
  template: |
    {{organization}} uses Network Infrastructure to a.    Monitor and control communications at the external boundary of the system and at key
          internal boundaries within the system;
    b.    Implement subnetworks for publicly accessible system components that are [Selection: physically; logically] separated from internal organizational networks; and
    c.    Connect to external networks or systems only through managed interfaces consisting of
          boundary protection devices arranged in accordance with an organizational
    security and
          privacy architecture.
     DESCR
- id: ssp_nistsp80053r5_control_sc_20_impl
  title: NIST SP 800-53 Rev 5 SC-20 Control Implementation
  format: markdown
  template: |
    {{organization}} uses Network Infrastructure to a.    Provide additional data origin authentication and integrity verification artifacts along with the
          authoritative name resolution data the system returns in response to external
    name/address
          resolution queries; and
    b.    Provide the means to indicate the security status of child zones and (if the child supports
          secure resolution services) to enable verification of a chain of trust among
    parent and child
          domains, when operating as part of a distributed, hierarchical namespace.
     DESCR
