id: app
title: Telco Room
type: project
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST SP 800-171) Compliance of Telco Room
    long: Generates compliance documentation of Telco Room as it pertains to managing
      the security of CUI (Controlled Unclassified Information) as per NIST SP 800-171
      controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    Telco Room is an on-premises data center for segrating computer servers, network
    equipment and telecommunications equipment from the rest of the facility.

    This application will make sure you are properly using Telco Room to protect CUI
    (Controlled Unclassified Information) as per NIST SP 800-171 controls.
questions:
- id: example
  title: Example Module
  type: module
  module-id: example
output:
- id: ssp_nist800171r1_3_8_1
  title: NIST SP 800-171 3.8.1 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses Telco Room to protect (i.e., physically control and securely store) system media containing CUI, both paper and digital.

    Telco Room is an on-premises data center for segrating computer servers, network equipment and telecommunications equipment from the rest of the facility.

- id: ssp_nist800171r1_3_8_2
  title: NIST SP 800-171 3.8.2 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses Telco Room to limit access to CUI on system media to authorized users.

    Telco Room is an on-premises data center for segrating computer servers, network equipment and telecommunications equipment from the rest of the facility.

- id: ssp_nist800171r1_3_10_1
  title: NIST SP 800-171 3.10.1 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses Telco Room to limit physical access to organizational systems, equipment, and the respective operating environments to authorized individuals.

    Telco Room is an on-premises data center for segrating computer servers, network equipment and telecommunications equipment from the rest of the facility.

- id: ssp_nist800171r1_3_10_2
  title: NIST SP 800-171 3.10.2 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses Telco Room to protect and monitor the physical facility and support infrastructure for organizational systems.

    Telco Room is an on-premises data center for segrating computer servers, network equipment and telecommunications equipment from the rest of the facility.

protocol:
- govready.com/apps/compliance/2017/nist-sp-800-171-r1-ssp
- govready.com/apps/compliance/2017/Telco-Room
