id: app
title: QNAP TS-670 (NAS)
type: project
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: stub
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-Glacier-Backup
  description:
    short: CUI (NIST SP 800-171) Compliance of QNAP TS-670 (NAS)
    long: Generates compliance documentation of QNAP TS-670 (NAS) as it pertains to
      managing the security of CUI (Controlled Unclassified Information) as per NIST
      SP 800-171 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: >-
    QNAP is network attached storage (NAS) device for storing digital files on a network.

    This application will make sure you are properly using QNAP TS-670 (NAS) to protect
    CUI (Controlled Unclassified Information) as per NIST SP 800-171 controls.
questions:
- id: example
  title: Example Module
  type: module
  module-id: example
output:
- id: ssp_nist800171r1_3_1_1
  title: NIST SP 800-171 3.1.1 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to limit system access to authorized users, processes acting on behalf of authorized users, or devices (including other systems).

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_1_2
  title: NIST SP 800-171 3.1.2 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to limit system access to the types of transactions and functions that authorized users are permitted to execute.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_1_3
  title: NIST SP 800-171 3.1.3 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to control the flow of CUI in accordance with approved authorizations.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_1_4
  title: NIST SP 800-171 3.1.4 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to separate the duties of individuals to reduce the risk of malevolent activity without collusion.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_1_7
  title: NIST SP 800-171 3.1.7 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to prevent non-privileged users from executing privileged functions and audit the execution of such functions.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_1_11
  title: NIST SP 800-171 3.1.11 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to terminate (automatically) a user session after a defined condition.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_1_12
  title: NIST SP 800-171 3.1.12 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to monitor and control remote access sessions.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_3_1
  title: NIST SP 800-171 3.3.1 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to create, protect, and retain system audit records to the extent needed to enable the monitoring, analysis, investigation, and reporting of unlawful, unauthorized, or inappropriate system activity.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_3_2
  title: NIST SP 800-171 3.3.2 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to ensure that the actions of individual system users can be uniquely traced to those users so they can be held accountable for their actions.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_3_4
  title: NIST SP 800-171 3.3.4 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to alert in the event of an audit process failure.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_3_8
  title: NIST SP 800-171 3.3.8 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to protect audit information and audit tools from unauthorized access, modification, and deletion.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_3_9
  title: NIST SP 800-171 3.3.9 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to limit management of audit functionality to a subset of privileged users.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_8_2
  title: NIST SP 800-171 3.8.2 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to limit access to CUI on system media to authorized users.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_8_7
  title: NIST SP 800-171 3.8.7 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to control the use of removable media on system components.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_8_8
  title: NIST SP 800-171 3.8.8 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to prohibit the use of portable storage devices when such devices have no identifiable owner.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_8_9
  title: NIST SP 800-171 3.8.9 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to protect the confidentiality of backup CUI at storage locations.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_13_1
  title: NIST SP 800-171 3.13.1 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to monitor, control, and protect communications (i.e., information transmitted or received by organizational systems) at the external boundaries and key internal boundaries of organizational systems.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_13_2
  title: NIST SP 800-171 3.13.2 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to employ architectural designs, software development techniques, and systems engineering principles that promote effective information security within organizational systems.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_13_4
  title: NIST SP 800-171 3.13.4 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to prevent unauthorized and unintended information transfer via shared system resources.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_13_6
  title: NIST SP 800-171 3.13.6 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to deny network communications traffic by default and allow network communications traffic by exception (i.e., deny all, permit by exception).

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_13_8
  title: NIST SP 800-171 3.13.8 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to implement cryptographic mechanisms to prevent unauthorized disclosure of CUI during transmission unless otherwise protected by alternative physical safeguards.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_13_9
  title: NIST SP 800-171 3.13.9 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to terminate network connections associated with communications sessions at the end of the sessions or after a defined period of inactivity.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_13_11
  title: NIST SP 800-171 3.13.11 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to employ FIPS-validated cryptography when used to protect the confidentiality of CUI.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

- id: ssp_nist800171r1_3_13_16
  title: NIST SP 800-171 3.13.16 Control Implementation
  format: markdown
  template: |+
    {{organization}} uses QNAP TS-670 (NAS) to protect the confidentiality of CUI at rest.

    QNAP is network attached storage (NAS) device for storing digital files on a network.

protocol:
- govready.com/apps/compliance/2017/nist-sp-800-171-r1-ssp
- govready.com/apps/compliance/2017/QNAP-TS-670-NAS
