id: app
title: AWS GovCloud
type: project
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: Beta
  version: 0.2
  source_url: https://github.com/GovReady/test-making-apps-from-matrix/tree/master/out/generic/AWS-GovCloud
  description:
    short: |
      CUI (800-171) Compliance of AWS GovCloud
    long: >
      Generates the compliance documentation of AWS GovCloud as it pertains
      to managing the security of CUI (Controlled Unclassified Information) as per
      NIST 800-171 controls.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: SysAdmin
introduction:
  format: markdown
  template: |
    Amazon describes AWS GovCloud (US) as "an isolated AWS region, subject to FedRAMP High and Moderate baselines, that allows customers to host sensitive Controlled Unclassified Information (CUI) and all types of regulated workloads...AWS GovCloud (US) gives vetted government customers and their partners the flexibility to architect secure cloud solutions that comply with: the FedRAMP High baseline." (https://aws.amazon.com/govcloud-us/)

    This application will make sure you are properly using AWS GovCloud to protect CUI.

questions:
- id: example
  title: Example Module
  type: module
  module-id: example

output:
- id: ssp_nist800171r1_3_1_1
  format: markdown
  template: |+
    3.1.1 Limit system access to authorized users, processes acting on behalf of authorized users, or devices (including other systems).

- id: ssp_nist800171r1_3_1_2
  format: markdown
  template: |+
    3.1.2 Limit system access to the types of transactions and functions that authorized users are permitted to execute.

- id: ssp_nist800171r1_3_1_3
  format: markdown
  template: |+
    3.1.3 Control the flow of CUI in accordance with approved authorizations.

- id: ssp_nist800171r1_3_1_4
  format: markdown
  template: |+
    3.1.4 Separate the duties of individuals to reduce the risk of malevolent activity without collusion.

- id: ssp_nist800171r1_3_1_5
  format: markdown
  template: |+
    3.1.5 Employ the principle of least privilege, including for specific security functions and privileged accounts.

- id: ssp_nist800171r1_3_1_6
  format: markdown
  template: |+
    3.1.6 Use non-privileged accounts or roles when accessing nonsecurity functions.

- id: ssp_nist800171r1_3_1_7
  format: markdown
  template: |+
    3.1.7 Prevent non-privileged users from executing privileged functions and audit the execution of such functions.

- id: ssp_nist800171r1_3_1_8
  format: markdown
  template: |+
    3.1.8 Limit unsuccessful logon attempts.

- id: ssp_nist800171r1_3_1_9
  format: markdown
  template: |+
    3.1.9 Provide privacy and security notices consistent with applicable CUI rules.

- id: ssp_nist800171r1_3_1_10
  format: markdown
  template: |+
    3.1.10 Use session lock with pattern-hiding displays to prevent access and viewing of data after period of inactivity.

- id: ssp_nist800171r1_3_1_11
  format: markdown
  template: |+
    3.1.11 Terminate (automatically) a user session after a defined condition.

- id: ssp_nist800171r1_3_1_12
  format: markdown
  template: |+
    3.1.12 Monitor and control remote access sessions.

- id: ssp_nist800171r1_3_1_13
  format: markdown
  template: |+
    3.1.13 Employ cryptographic mechanisms to protect the confidentiality of remote access sessions.

- id: ssp_nist800171r1_3_1_14
  format: markdown
  template: |+
    3.1.14 Route remote access via managed access control points.

- id: ssp_nist800171r1_3_1_15
  format: markdown
  template: |+
    3.1.15 Authorize remote execution of privileged commands and remote access to security-relevant information.

- id: ssp_nist800171r1_3_1_16
  format: markdown
  template: |+
    3.1.16 Authorize wireless access prior to allowing such connections.

- id: ssp_nist800171r1_3_1_17
  format: markdown
  template: |+
    3.1.17 Protect wireless access using authentication and encryption.

- id: ssp_nist800171r1_3_1_18
  format: markdown
  template: |+
    3.1.18 Control connection of mobile devices.

- id: ssp_nist800171r1_3_1_19
  format: markdown
  template: |+
    3.1.19 Encrypt CUI on mobile devices and mobile computing platforms. [Footnote: Mobile devices and mobile computing platforms include, for example, smartphones, tablets, E-readers, and notebook computers.]

- id: ssp_nist800171r1_3_1_20
  format: markdown
  template: |+
    3.1.20 Verify and control/limit connections to and use of external systems.

- id: ssp_nist800171r1_3_1_21
  format: markdown
  template: |+
    3.1.21 Limit use of organizational portable storage devices on external systems.

- id: ssp_nist800171r1_3_1_22
  format: markdown
  template: |+
    3.1.22 Control CUI posted or processed on publicly accessible systems.

- id: ssp_nist800171r1_3_3_1
  format: markdown
  template: |+
    3.3.1 Create, protect, and retain system audit records to the extent needed to enable the monitoring, analysis, investigation, and reporting of unlawful, unauthorized, or inappropriate system activity.

- id: ssp_nist800171r1_3_3_2
  format: markdown
  template: |+
    3.3.2 Ensure that the actions of individual system users can be uniquely traced to those users so they can be held accountable for their actions.

- id: ssp_nist800171r1_3_3_3
  format: markdown
  template: |+
    3.3.3 Review and update audited events.

- id: ssp_nist800171r1_3_3_4
  format: markdown
  template: |+
    3.3.4 Alert in the event of an audit process failure.

- id: ssp_nist800171r1_3_3_5
  format: markdown
  template: |+
    3.3.5 Correlate audit review, analysis, and reporting processes for investigation and response to indications of inappropriate, suspicious, or unusual activity.

- id: ssp_nist800171r1_3_3_6
  format: markdown
  template: |+
    3.3.6 Provide audit reduction and report generation to support on-demand analysis and reporting.

- id: ssp_nist800171r1_3_3_7
  format: markdown
  template: |+
    3.3.7 Provide a system capability that compares and synchronizes internal system clocks with an authoritative source to generate time stamps for audit records.

- id: ssp_nist800171r1_3_3_8
  format: markdown
  template: |+
    3.3.8 Protect audit information and audit tools from unauthorized access, modification, and deletion.

- id: ssp_nist800171r1_3_3_9
  format: markdown
  template: |+
    3.3.9 Limit management of audit functionality to a subset of privileged users.

- id: ssp_nist800171r1_3_5_1
  format: markdown
  template: |+
    3.5.1 Identify system users, processes acting on behalf of users, or devices.

- id: ssp_nist800171r1_3_5_2
  format: markdown
  template: |+
    3.5.2 Authenticate (or verify) the identities of those users, processes, or devices, as a prerequisite to allowing access to organizational systems.

- id: ssp_nist800171r1_3_5_3
  format: markdown
  template: >+
    3.5.3 Use multifactor authentication [Footnote: Multifactor authentication requires
    two or more different factors to achieve authentication. The factors include:
    something you know (e.g., password/PIN); something you have (e.g., cryptographic
    identification device, token); or something you are (e.g., biometric). The requirement
    for multifactor authentication should not be interpreted as requiring federal
    Personal Identity Verification (PIV) card or Department of Defense Common Access
    Card (CAC)like solutions. A variety of multifactor solutions (including those
    with replay resistance) using tokens and biometrics are commercially available.
    Such solutions may employ hard tokens (e.g., smartcards, key fobs, or dongles)
    or soft tokens to store user credentials.] for local and network access [Footnote:
    Local access is any access to a system by a user (or process acting on behalf
    of a user) communicating through a direct connection without the use of a network.
    Network access is any access to a system by a user (or a process acting on behalf
    of a user) communicating through a network (e.g., local area network, wide area
    network, Internet).] to privileged accounts and for network access to non-privileged
    accounts.

- id: ssp_nist800171r1_3_5_4
  format: markdown
  template: |+
    3.5.4 Employ replay-resistant authentication mechanisms for network access to privileged and nonprivileged accounts.

- id: ssp_nist800171r1_3_5_5
  format: markdown
  template: |+
    3.5.5 Prevent reuse of identifiers for a defined period.

- id: ssp_nist800171r1_3_5_6
  format: markdown
  template: |+
    3.5.6 Disable identifiers after a defined period of inactivity.

- id: ssp_nist800171r1_3_5_7
  format: markdown
  template: |+
    3.5.7 Enforce a minimum password complexity and change of characters when new passwords are created.

- id: ssp_nist800171r1_3_5_8
  format: markdown
  template: |+
    3.5.8 Prohibit password reuse for a specified number of generations.

- id: ssp_nist800171r1_3_5_9
  format: markdown
  template: |+
    3.5.9 Allow temporary password use for system logons with an immediate change to a permanent password.

- id: ssp_nist800171r1_3_5_10
  format: markdown
  template: |+
    3.5.10 Store and transmit only cryptographically-protected passwords.

- id: ssp_nist800171r1_3_5_11
  format: markdown
  template: |+
    3.5.11 Obscure feedback of authentication information.

- id: ssp_nist800171r1_3_8_1
  format: markdown
  template: |+
    3.8.1 Protect (i.e., physically control and securely store) system media containing CUI, both paper and digital.

- id: ssp_nist800171r1_3_8_2
  format: markdown
  template: |+
    3.8.2 Limit access to CUI on system media to authorized users.

- id: ssp_nist800171r1_3_8_3
  format: markdown
  template: |+
    3.8.3 Sanitize or destroy system media containing CUI before disposal or release for reuse.

- id: ssp_nist800171r1_3_8_4
  format: markdown
  template: |+
    3.8.4 Mark media with necessary CUI markings and distribution limitations. [Footnote: The implementation of this requirement is per marking guidance in the 32 CFR, Part 2002, and the CUI Registry.]

- id: ssp_nist800171r1_3_8_5
  format: markdown
  template: |+
    3.8.5 Control access to media containing CUI and maintain accountability for media during transport outside of controlled areas.

- id: ssp_nist800171r1_3_8_6
  format: markdown
  template: |+
    3.8.6 Implement cryptographic mechanisms to protect the confidentiality of CUI stored on digital media during transport unless otherwise protected by alternative physical safeguards.

- id: ssp_nist800171r1_3_8_7
  format: markdown
  template: |+
    3.8.7 Control the use of removable media on system components.

- id: ssp_nist800171r1_3_8_8
  format: markdown
  template: |+
    3.8.8 Prohibit the use of portable storage devices when such devices have no identifiable owner.

- id: ssp_nist800171r1_3_8_9
  format: markdown
  template: |+
    3.8.9 Protect the confidentiality of backup CUI at storage locations.

- id: ssp_nist800171r1_3_9_1
  format: markdown
  template: |+
    3.9.1 Screen individuals prior to authorizing access to organizational systems containing CUI.

- id: ssp_nist800171r1_3_9_2
  format: markdown
  template: |+
    3.9.2 Ensure that CUI and organizational systems containing CUI are protected during and after personnel actions such as terminations and transfers.

- id: ssp_nist800171r1_3_10_1
  format: markdown
  template: |+
    3.10.1 Limit physical access to organizational systems, equipment, and the respective operating environments to authorized individuals.

- id: ssp_nist800171r1_3_10_2
  format: markdown
  template: |+
    3.10.2 Protect and monitor the physical facility and support infrastructure for organizational systems.

- id: ssp_nist800171r1_3_10_3
  format: markdown
  template: |+
    3.10.3 Escort visitors and monitor visitor activity.

- id: ssp_nist800171r1_3_10_4
  format: markdown
  template: |+
    3.10.4 Maintain audit logs of physical access.

- id: ssp_nist800171r1_3_10_5
  format: markdown
  template: |+
    3.10.5 Control and manage physical access devices.

- id: ssp_nist800171r1_3_10_6
  format: markdown
  template: |+
    3.10.6 Enforce safeguarding measures for CUI at alternate work sites (e.g., telework sites).

- id: ssp_nist800171r1_3_12_1
  format: markdown
  template: |+
    3.12.1 Periodically assess the security controls in organizational systems to determine if the controls are effective in their application.

- id: ssp_nist800171r1_3_12_2
  format: markdown
  template: |+
    3.12.2 Develop and implement plans of action designed to correct deficiencies and reduce or eliminate vulnerabilities in organizational systems.

- id: ssp_nist800171r1_3_12_3
  format: markdown
  template: |+
    3.12.3 Monitor security controls on an ongoing basis to ensure the continued effectiveness of the controls.

- id: ssp_nist800171r1_3_12_4
  format: markdown
  template: >+
    3.12.4 Develop, document, and periodically update system security plans that describe
    system boundaries, system environments of operation, how security requirements
    are implemented, and the relationships with or connections to other systems. [Footnote:
    There is no prescribed format or specified level of detail for system security
    plans. However, organizations must ensure that the required information in 3.12.4
    is appropriately conveyed in those plans.]

- id: ssp_nist800171r1_3_13_1
  format: markdown
  template: |+
    3.13.1 Monitor, control, and protect communications (i.e., information transmitted or received by organizational systems) at the external boundaries and key internal boundaries of organizational systems.

- id: ssp_nist800171r1_3_13_2
  format: markdown
  template: |+
    3.13.2 Employ architectural designs, software development techniques, and systems engineering principles that promote effective information security within organizational systems.

- id: ssp_nist800171r1_3_13_3
  format: markdown
  template: |+
    3.13.3 Separate user functionality from system management functionality.

- id: ssp_nist800171r1_3_13_4
  format: markdown
  template: |+
    3.13.4 Prevent unauthorized and unintended information transfer via shared system resources.

- id: ssp_nist800171r1_3_13_5
  format: markdown
  template: |+
    3.13.5 Implement subnetworks for publicly accessible system components that are physically or logically separated from internal networks.

- id: ssp_nist800171r1_3_13_6
  format: markdown
  template: |+
    3.13.6 Deny network communications traffic by default and allow network communications traffic by exception (i.e., deny all, permit by exception).

- id: ssp_nist800171r1_3_13_7
  format: markdown
  template: |+
    3.13.7 Prevent remote devices from simultaneously establishing non-remote connections with organizational systems and communicating via some other connection to resources in external networks.

- id: ssp_nist800171r1_3_13_8
  format: markdown
  template: |+
    3.13.8 Implement cryptographic mechanisms to prevent unauthorized disclosure of CUI during transmission unless otherwise protected by alternative physical safeguards.

- id: ssp_nist800171r1_3_13_9
  format: markdown
  template: |+
    3.13.9 Terminate network connections associated with communications sessions at the end of the sessions or after a defined period of inactivity.

- id: ssp_nist800171r1_3_13_10
  format: markdown
  template: |+
    3.13.10 Establish and manage cryptographic keys for cryptography employed in organizational systems.

- id: ssp_nist800171r1_3_13_11
  format: markdown
  template: |+
    3.13.11 Employ FIPS-validated cryptography when used to protect the confidentiality of CUI.

- id: ssp_nist800171r1_3_13_12
  format: markdown
  template: >+
    3.13.12 Prohibit remote activation [Footnote: Dedicated video conferencing systems,
    which rely on one of the participants calling or connecting to the other party
    to activate the video conference, are excluded.] of collaborative computing devices
    and provide indication of devices in use to users present at the device.

- id: ssp_nist800171r1_3_13_13
  format: markdown
  template: |+
    3.13.13 Control and monitor the use of mobile code.

- id: ssp_nist800171r1_3_13_14
  format: markdown
  template: |+
    3.13.14 Control and monitor the use of Voice over Internet Protocol (VoIP) technologies.

- id: ssp_nist800171r1_3_13_15
  format: markdown
  template: |+
    3.13.15 Protect the authenticity of communications sessions.

- id: ssp_nist800171r1_3_13_16
  format: markdown
  template: |+
    3.13.16 Protect the confidentiality of CUI at rest.

